#! /usr/bin/perl
use strict;

# Parse command line
my $epuck=shift;
$epuck=int($1) if ($epuck =~ /(\d+)/);
if (($epuck<1) || ($epuck>200)) {
	print 'Usage:', "\n";
	print '    epuckconnect EPUCK_NUMBER [EPUCK_NUMBER2 EPUCK_NUMBER3 ...]', "\n";
	print 'EPUCK_NUMBERs are between 1 and 200.', "\n";
	print 'Example (for e-puck 127):', "\n";
	print '    epuckconnect 127', "\n";
	exit(1);
}

# Determine PIN code
my $pincode=$epuck;
while (length $pincode < 4) {
	$pincode='0'.$pincode;
}

# Connect to the e-puck to set up the Bluetooth PIN
print 'Switch on your e-puck ', $epuck, '.', "\n";
print 'While I\'m trying to connect to your e-puck, you may have to enter its Bluetooth PIN code "', $pincode, '".', "\n";
open(F, '<', '/dev/rfcomm'.$epuck) || die 'Unable to connect to your e-puck. Are you sure your e-puck is switched on?';
print 'I\'m connected', "\n";
close F;

# Write the gtkterm configuration
open(F, '>', $ENV{'HOME'}.'/.gtktermrc') || die 'Unable to write '.$ENV{'HOME'}.'/.gtktermrc';
print F <<EOM1;
[default]
port	= /dev/rfcomm$epuck
speed	= 115200
bits	= 8
stopbits	= 1
parity	= none
flow	= none
wait_delay	= 0
wait_char	= -1
echo	= False
crlfauto	= False
font	= "Nimbus Mono L, 14"
term_transparency	= False
term_show_cursor	= True
term_rows	= 80
term_columns	= 25
term_visual_bell	= True
term_foreground_red	= 43253
term_foreground_blue	= 43253
term_foreground_green	= 43253
term_background_red	= 0
term_background_blue	= 0
term_background_green	= 0
term_background_saturation	= 0.500000
EOM1
close F;

# Write the minicom configuration
open(F, '>', $ENV{'HOME'}.'/.minirc.dfl') || die 'Unable to write '.$ENV{'HOME'}.'/.minirc.dfl';
print F <<EOM2;
pr port	/dev/rfcomm$epuck
pr lock	/var/lock
pu baudrate	115200
pu minit
pu mreset
pu mdialpre
pu mdialsuf
pu mdialpre2
pu mdialsuf2
pu mdialpre3
pu mdialsuf3
pu mconnect
pu mnocon1
pu mnocon2
pu mnocon3
pu mnocon4
pu mhangup
pu mdialcan
pu mretries	1
pu rtscts	No
pu xonxoff	No
EOM2
close F;

# Let the user know that everything is all right
print 'E-puck ', $epuck, ' is now set as default e-puck for this computer, and you can', "\n";
print 'use one of the following programs to communicate with your e-puck:', "\n";
print '    minicom', "\n";
print '    picocom /dev/rfcomm', $epuck, "\n";
print '    gtkterm', "\n";
print 'or the following program to upload a new program onto your e-puck:', "\n";
print '    epuckupload -f my_new_program.hex ', $epuck, "\n";

