#! /bin/bash


# MODIFY THE FOLLOWING LINES to set the path to your e-puck directory (containing the development tree and the tools) and to your pic30-elf directory (C30 compiler)
export EPUCKBASEPATH=$PWD/Epuck/Tools
export C30PATH=$PWD/Epuck/Tools/pic30-elf

# Setting up paths
export PATH=$EPUCKBASEPATH/epuck:$PATH
export PATH=$C30PATH:$C30PATH/pic30-elf:$PATH

# Colored shell
export PS1="\[\e[34m\]\u@\h:\w> \[\e[0m\]"

echo "Epuck environment set"

sudo rfcomm bind 55 08:00:17:20:49:AB 1
sudo rfcomm bind 83 08:00:17:20:53:16 1
sudo rfcomm bind 130 10:00:E8:C3:17:11 1
sudo rfcomm bind 149 08:00:17:20:5F:37 1

echo "Bind rfcomm done"



